import re
from playwright.sync_api import Page, expect

def test_mrz(page: Page) -> None:
    page.goto("https://emvlab.org/")
    page.get_by_role("link", name="mrz calculator", exact=True).click()
    page.locator("#name").click()
    page.locator("#name").clear()
    page.locator("#name").fill("Quincy Fawcett")
    page.get_by_role("radio", name="Male", exact=True).check()
    page.locator("#dob").click()
    page.locator("#dob").clear()
    page.locator("#dob").fill("900106")
    page.locator("#expirydate").click()
    page.locator("#expirydate").clear()
    page.locator("#expirydate").fill("160101")
    page.locator("#passno").click()
    page.locator("#passno").clear()
    page.locator("#passno").fill("242988576")
    page.locator("#nationality").click()
    page.locator("#nationality").clear()
    page.locator("#nationality").fill("GBR")
    page.locator("#issuer").click()
    page.locator("#issuer").clear()
    page.locator("#issuer").fill("GBR")
    page.locator("#extra").click()
    page.locator("#extra").clear()
    page.locator("#extra").fill("<<<<<<<<<<<<<<")
    page.get_by_role("button", name="Calculate MRZ").click()
    expect(page.locator("#mrz")).to_contain_text("P<GBRFAWCETT<<QUINCY<<<<<<<<<<<<<<<<<<<<<<<< 2429885765GBR9001066M1601013<<<<<<<<<<<<<<00")